version: '3.9'

services:
  resource-user-db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3307:3306"
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - resource-network
volumes:
  user-db-data:
    driver: local
networks:
  resource-network:
    external:
      name: resource-network
