spring:
  config:
    import: optional:configserver:http://localhost:8090
  datasource:
    url: jdbc:mariadb://localhost:3307/user-db?createDatabaseIfNotExist=true
    username: resource-user
    password: resource-user
application:
  security:
    issuer-url: http://localhost:8088
